### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by GrigorenkoSergey** [staya-bomjei/toxin#40]
* выровнять по ПП
 * ввод пароля звездочками
 * разделять имена файлов, вроде thumbnail-1
 * поменять картинки на другое расширение в соответствии с [BP](https://github.com/fullstack-development/front-end-best-practices/tree/master/HTML#3.5)
 * задай ширину страницы 1440px, чтобы не приходилось постоянно вводить самому )
 
![Screenshot from 2022-01-14 16-30-32](https://user-images.githubusercontent.com/52627852/149540937-646a101a-94af-4c59-857c-1902fb774f02.png)

**Comment by GrigorenkoSergey** [comment]
* Не max-width, a width для UI-Kit. Чтобы проверить по ПП мне нужно открыть консоль и установить ширину элемента HTML вручную, а мне лень )
* не использовать отрицательным margin, [BP](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#2.4). Да и вообще, для чего тебе нужен cards-row? ![cards-negative-margin](https://user-images.githubusercontent.com/52627852/149917883-0cb4181f-c923-461e-92ed-a4c956c0fe46.png)
* не бывает св-ва `flex-grow: auto`.  ![cards-flex-grow](https://user-images.githubusercontent.com/52627852/149917677-8271f3bb-a63f-4272-a8ee-c94c92b1445c.png)
* проверь весь проект на наличие лишних импортов и инклудов ![cards-includes](https://user-images.githubusercontent.com/52627852/149918060-69b5f536-34e8-4378-8134-de6982bd473e.png)

**Comment by staya-bomjei** [comment]
Честно говоря, я облетел все файлы и не нашел лишних импортов (кроме одного инклюда в scss), а на представленной картинке нет лишних инклудов. `Include dropdown`  используется для отображения календаря (просто с модификатором, который прячет всё, кроме, собственно, календаря). Так же некоторые компоненты импортируют другие компоненты внутри себя, это сделано для того, чтобы не беспокоится о том, были ли подключены в странице, использующей компонент, все подкомпоненты.

**Comment by GrigorenkoSergey** [comment]
О, пардон. В sign-in и sign-up не разглядел окончания.
