### ISSUE TITLE
room-thumbnail

### ISSUE THREAD

**Issue by GrigorenkoSergey** [staya-bomjei/toxin#57]
Передавать через настройки
![room-thumbnail](https://user-images.githubusercontent.com/52627852/151375835-2e792b72-4182-4abd-8cc5-104b46f4ffd4.png)

**Comment by staya-bomjei** [comment]
Это issue и [#56](https://github.com/staya-bomjei/toxin/issues/56) , они уже были выполнены во время прошлого review ([#56](https://github.com/staya-bomjei/toxin/issues/56) не полностью), очень жаль, что push где-то заблудился (или я его вовсе не запушил?) 😅
